version: '3.8'

services: 
  backend:
    container_name: educational_api
    image: educational_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/api/usr/app
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=educational-db
