name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: admin
          POSTGRESQL_PASSWORD: admin
          POSTGRESQL_DATABASE: educational-db

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
       
      - run: yarn install --frozen-lockfile
      - run: yarn prisma migrate deploy
        env:
            PASSWORD_SALT: 10
            DATABASE_URL: "postgresql://admin:admin@localhost:5432/educational-db?schema=public"
            CORS: -*-
            JWT_SECRET: teste123
            JWT_TOKEN_EXPIRES_IN: 10m
            JWT_REFRESH_TOKEN_EXPIRES_IN: 60m
      - run: yarn test:e2e
        env:
            PASSWORD_SALT: 10
            DATABASE_URL: "postgresql://admin:admin@localhost:5432/educational-db?schema=public"
            CORS: -*-
            JWT_SECRET: teste123
            JWT_TOKEN_EXPIRES_IN: 10m
            JWT_REFRESH_TOKEN_EXPIRES_IN: 60m
        